apiVersion: v1
kind: Service
metadata:
  name: replica-test
  namespace: dashboard
spec:
  type: ClusterIP
  selector:
    app: replica-test
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
